# Generated by Django 3.1.3 on 2020-12-29 15:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=148, verbose_name='Заголовок карточки')),
                ('text', models.TextField(verbose_name='Текст карточки')),
                ('color', models.CharField(blank=True, choices=[('RED', '#e53935'), ('PINK', '#d81b60'), ('DPPRPR', '#5e35b1'), ('INDIGO', '#3949ab'), ('LGHTBLUE', '#039be5'), ('GREEN', '#43a047'), ('YELLOW', '#fdd835'), ('ORANGE', '#fb8c00')], max_length=10, verbose_name='Цвет карточки')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 29, 17, 4, 19, 418389))),
                ('edited', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Автор', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
