# Generated by Django 3.1.3 on 2020-12-30 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(blank=True, max_length=10, verbose_name='Цвет карточки'),
        ),
        migrations.AlterField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 30, 20, 38, 37, 176964)),
        ),
    ]
