# Generated by Django 3.1.3 on 2020-12-30 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0002_auto_20201230_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 31, 1, 14, 37, 426206)),
        ),
    ]
